# Generated by Django 5.1.5 on 2025-01-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tg_nick',
        ),
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, help_text='Укажите телеграм сhat-id', max_length=50, null=True, verbose_name='Телеграм сhat-id'),
        ),
    ]
