# Generated by Django 5.1.5 on 2025-02-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='periodicity',
            field=models.IntegerField(default=1, help_text='Укажите периодичность выполнения в днях', verbose_name='Периодичность'),
        ),
    ]
