# Generated by Django 5.1.5 on 2025-02-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_usefulhabit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='duration',
            field=models.IntegerField(help_text='Укажите продолжительность в секундах', verbose_name='Продолжительность'),
        ),
    ]
